# markdown: rdiscount
permalink: /:year/:month/:title/
url: http://scsidisk.github.io
author: scsidisk
highlighter: pygments
# pygments: true
markdown: redcarpet
redcarpet: 
    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
paginate: 24
disqus_shortname: scsidiskgithubio
sitename: ScsiDisk's Blog

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad,asc
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=coderay
    - coderay-css=style

