permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# 站点设置
title: "Scsidisk's Blog"
email: scsidisk@gmail.com
description: "scsidisk 的博客"
keywords: "scsidisk"

# 用户信息设置
weibo_username: Scsidisk
github_username: scsidisk

# Markdown设置
kramdown:
  input:  GFM
  #use_coderay: true
  # coderay:
  #   coderay_line_numbers:  nil



# 地址设置
baseurl: ""
url: "http://127.0.0.1:4000"


# 分页设置
paginate: 10
# paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

gems:
 - jekyll-coffeescript
 - jekyll-paginate

# url: http://scsidisk.github.io
disqus_shortname: scsidiskgithubio


# duoshuo设置
# duoshuo_shortname:

# 百度统计设置
# baidu_analysis:
