= 企业管理的KPI陷阱
简江
:layout: post
:category: Management
:tags: KPI, Management

天下网商特邀作者 简江（微信号：jianjiangvc）

KPI，Key Performance Indictor，关键绩效指标。是衡量部门、团队和员工绩效最重要、最直接的考核标准。KPI和KPI目标的制定应该遵循SMART原则，即具体、可衡量、可达到、相关和有时效。

做任何事情都必须有可评估目标，KPI作为最关键评估指标，就应该能够直接反映部门、团队和个人目标的达成情况。KPI应该和企业战略，和切合于战略的阶段性战术越贴近越好。

但是在实际操作中，我们经常会发现KPI评估体系被“滥用”、“乱用”的情况。制定和执行KPI评估常见两种误区，第一种误区叫做“忘本”，实际不是KPI本身的问题，而是企业管理层没有搞清楚企业战略目标是什么；第二种误区叫做“偏离”，常见于KPI具体细化分解落实的时候，和KPI制定的初衷出现了偏差，甚至经过细化后的KPI，在实际执行中产生冲突，以及依据细化后KPI，产生偏离企业战略战术原则的行动。

首先说“忘本”。每个企业都应该有它的价值观，这个价值观不是口号，而是用以衡量何为企业核心价值、立足之本的基础原则。譬如Amazon把User Experience作为它的核心价值观之一。因为Amazon认为UE是它的核心竞争力，所以一旦有其它目标和UE冲突，通常会向UE让位。所以企业的核心KPI，必须服从于企业的核心价值观；反之，企业核心价值观，也必须在核心KPI中有所体现。

譬如在一个市场的萌芽期到成长期，即开拓期和圈地竞争期，由于市场远远没有饱和，消费者没有充分的选择权，产品毛利较高，营销驱动重于产品驱动，所以这个阶段企业往往以销量作为核心KPI；而在市场发展的成熟期，由于竞争愈发激烈，毛利降低，单靠营销驱动会越来越难以为继，就需要在产品上做差异化乃至破坏性创新，才能产生新的溢价，在这个阶段，产品创新重于营销创新。所以在不同的阶段，企业战略的核心必须转变，KPI也需要随之转变，而实践困难是销售驱动的企业在转为产品服务驱动企业的时候，往往只是口头上喊喊口号，实质不会有任何动作，也不会体现在企业KPI上，这样的的战略转型往往在执行中无法落实。

所以，表面上看起来是KPI不清晰，KPI无法反映战略，实际上是企业战略目标不清晰。KPI制定中最忌讳的就是舍本逐末。在市场转到产品与服务驱动的时候，销售额是企业创造价值的变现，而不是营销能力的变现，所以如果KPI不反映企业的前段价值创造，而死卡末端变现，反而会损害企业的核心价值。譬如现在的中高档餐馆，卖服务重于卖菜品，服务员既然是“服务提供”方，其创造的价值就应该是“服务”，核心KPI也应该与服务而不是与销售直接相关。如果以销售作为服务员的考核指标，那么服务员就会费尽心机向消费者推销菜品，并且尽量避免消费者退菜，这实质上降低了消费者对服务的体验，同时降低了餐馆的服务价值，小处鸡贼，得不偿失。

再说“偏离”。绩效评估通常是人事部门的工作，无论是人事部门，还是基层部门，经常会把绩效评估当做一个任务来完成，很少有企业意识到绩效是企业阶段性行动的指挥棒。绩效评估“任务”下发后，人事部门和各个业务部门的绩效相关人员，往往只追求形式上合规，如果人事部门要求高，大量精力会花在如何符合SMART原则、具体的业务目标如何制定，而没有人对细化后的KPI指标是否符合企业阶段性战略，以及相配合的战术目标负责。

这就会导致三类常见问题，第一类常见问题是细化后的KPI目标之间存在冲突，譬如在上面服务员那个例子中，既要求服务质量，又要服务员背绩效指标，在实践中就是冲突的，但是这个冲突并非完全不能调和，在具体的实践中，需要更细节的战术指导原则；第二类常见问题是KPI不完备，当一个战略被细化的时候，并非所有纬度的目标都很容易SMART，有些目标SMART非常困难，而负责绩效的人员在这种情况下常常选择删除难以被SMART的目标，导致KPI不完备，后果显而易见。现代企业在实际运作过程中，部门协作必须列入关键性业务考量目标，如果部门之间各自为政、各为其小利益行事，企业就会变得非常官僚效率低内耗高，而这方面的KPI经常在KPI制定中被忽略；第三类常见问题是KPI被操纵，部门为了更容易完成绩效，避免矛盾冲突和责任承担，往往会删除KPI中容易“出问题”的部门，降低有挑战KPI的目标难度。

绩效目标制定与考核行动通常由业务职能部门主导，人事部门只起到发起、辅助和检查的作用。在很多企业里，无论是高级管理层、还是企业战略部门，都把KPI作为人事部的一项任务，而人事部显然不能为KPI是否符合企业战略负责。更有甚者，不完善的KPI体系，异化成了某些部门实现小利益、打击异己、逃避责任的工具。

在一个更理想的企业治理架构里，员工是由激励来驱动的，企业管理制度退后，由规定“必须做什么”退后到规定“不能做什么”，一些成功的经验被编制成执行建议，而不是执行要求。员工日常工作靠热情和喜爱做事，而不是靠绩效和制度的压力做事。这种模式看起来乌托邦，其实很快就会有非常多的实践案例。

归根结底，KPI是工业时代发展出来的管理工具，任何工具都会有其局限性，需要与时俱进，最终都是为了企业的战略目标服务，如果由于使用了不恰当的工具、或者工具使用不当，对企业发展造成了障碍或者打击，反而偏离了我们使用工具的原本目标。KPI在执行中处处都有陷阱，小心不要掉坑里。

